### ISSUE TITLE
WebsocketNotConnectedException 

### ISSUE THREAD

**Issue by rahelarnold98** [vGsteiger/BachelorsThesisContribution#1]
Hi,
When I have a running cineast instance and want to connect the evaluation application, I always get "Connection unsuccessful", whereas the cineast page shows the connection. I assume the problem is that the connection of the `wsClient` in [QueryExecutioner.kt](https://github.com/vGsteiger/BachelorsThesisContribution/blob/main/tempAlgEval/src/main/kotlin/query/websocket/QueryExecutioner.kt) gets created with `connect` and not with `connectBlocking`.
Have you already had this problem?

**Comment by vGsteiger** [comment]
Hi Rahel,

I personally haven't encountered that issue. How are you running the Cineast instance? For me it both worked with a local instance as well as a server instance. However, it might be that Cineast has been updated in the meantime (I haven't touched this code since the last commit). Have you tried using it with `connectBlocking` instead of `connect`? Did that fix the issue?  

If it did, would you mind creating a PR to fix this? 

Thanks a lot and if you have any other questions please feel free to ask anytime or write me an email.

**Comment by rahelarnold98** [comment]
Solved by #2
